// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assignments.sql

package repository

import (
	"context"
)

const createAssignment = `-- name: CreateAssignment :exec
INSERT INTO assignments (
    room_id,
    giver_user_id,
    receiver_user_id,
    wish_id
)
VALUES ($1, $2, $3, $4)
`

type CreateAssignmentParams struct {
	RoomID         int64 `json:"room_id"`
	GiverUserID    int64 `json:"giver_user_id"`
	ReceiverUserID int64 `json:"receiver_user_id"`
	WishID         int64 `json:"wish_id"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) error {
	_, err := q.db.Exec(ctx, createAssignment,
		arg.RoomID,
		arg.GiverUserID,
		arg.ReceiverUserID,
		arg.WishID,
	)
	return err
}

const hasAssignments = `-- name: HasAssignments :one
SELECT EXISTS (
    SELECT 1
    FROM assignments
    WHERE room_id = $1
)
`

func (q *Queries) HasAssignments(ctx context.Context, roomID int64) (bool, error) {
	row := q.db.QueryRow(ctx, hasAssignments, roomID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAssignmentsForRoom = `-- name: ListAssignmentsForRoom :many
SELECT
    a.giver_user_id,
    a.receiver_user_id,
    w.text AS wish_text
FROM assignments a
JOIN wishes w ON w.id = a.wish_id
WHERE a.room_id = $1
`

type ListAssignmentsForRoomRow struct {
	GiverUserID    int64  `json:"giver_user_id"`
	ReceiverUserID int64  `json:"receiver_user_id"`
	WishText       string `json:"wish_text"`
}

func (q *Queries) ListAssignmentsForRoom(ctx context.Context, roomID int64) ([]ListAssignmentsForRoomRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentsForRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignmentsForRoomRow
	for rows.Next() {
		var i ListAssignmentsForRoomRow
		if err := rows.Scan(&i.GiverUserID, &i.ReceiverUserID, &i.WishText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
