// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package repository

import (
	"context"
)

const isUserInRoom = `-- name: IsUserInRoom :one
SELECT EXISTS (
    SELECT 1
    FROM room_members
    WHERE room_id = $1 AND user_id = $2
)
`

type IsUserInRoomParams struct {
	RoomID int64 `json:"room_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) IsUserInRoom(ctx context.Context, arg IsUserInRoomParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserInRoom, arg.RoomID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const joinRoom = `-- name: JoinRoom :exec
INSERT INTO room_members (room_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type JoinRoomParams struct {
	RoomID int64 `json:"room_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) JoinRoom(ctx context.Context, arg JoinRoomParams) error {
	_, err := q.db.Exec(ctx, joinRoom, arg.RoomID, arg.UserID)
	return err
}

const leaveRoom = `-- name: LeaveRoom :exec
DELETE FROM room_members
WHERE room_id = $1 AND user_id = $2
`

type LeaveRoomParams struct {
	RoomID int64 `json:"room_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) LeaveRoom(ctx context.Context, arg LeaveRoomParams) error {
	_, err := q.db.Exec(ctx, leaveRoom, arg.RoomID, arg.UserID)
	return err
}

const listRoomMembers = `-- name: ListRoomMembers :many
SELECT u.id, u.telegram_user_id, u.username, u.created_at
FROM users u
JOIN room_members rm ON rm.user_id = u.id
WHERE rm.room_id = $1
`

func (q *Queries) ListRoomMembers(ctx context.Context, roomID int64) ([]User, error) {
	rows, err := q.db.Query(ctx, listRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TelegramUserID,
			&i.Username,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
