// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"
)

type Assignment struct {
	RoomID         int64     `json:"room_id"`
	GiverUserID    int64     `json:"giver_user_id"`
	ReceiverUserID int64     `json:"receiver_user_id"`
	WishID         int64     `json:"wish_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type Room struct {
	ID          int64     `json:"id"`
	CreatedBy   int64     `json:"created_by"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	DeletedAt   time.Time `json:"deleted_at"`
}

type RoomMember struct {
	RoomID   int64     `json:"room_id"`
	UserID   int64     `json:"user_id"`
	JoinedAt time.Time `json:"joined_at"`
}

type User struct {
	ID             int64     `json:"id"`
	TelegramUserID int64     `json:"telegram_user_id"`
	Username       *string   `json:"username"`
	CreatedAt      time.Time `json:"created_at"`
}

type Wish struct {
	ID        int64     `json:"id"`
	RoomID    int64     `json:"room_id"`
	UserID    int64     `json:"user_id"`
	Text      string    `json:"text"`
	CreatedAt time.Time `json:"created_at"`
}
