// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	CountMissingWishes(ctx context.Context, roomID int64) (int64, error)
	CreateAssignment(ctx context.Context, arg CreateAssignmentParams) error
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetRoomByID(ctx context.Context, id int64) (Room, error)
	GetRoomsByCreator(ctx context.Context, createdBy int64) ([]Room, error)
	GetUserByTelegramID(ctx context.Context, telegramUserID int64) (User, error)
	GetWish(ctx context.Context, arg GetWishParams) (Wish, error)
	HasAssignments(ctx context.Context, roomID int64) (bool, error)
	IsUserInRoom(ctx context.Context, arg IsUserInRoomParams) (bool, error)
	JoinRoom(ctx context.Context, arg JoinRoomParams) error
	LeaveRoom(ctx context.Context, arg LeaveRoomParams) error
	ListAssignmentsForRoom(ctx context.Context, roomID int64) ([]ListAssignmentsForRoomRow, error)
	ListRoomMembers(ctx context.Context, roomID int64) ([]User, error)
	ListRooms(ctx context.Context) ([]Room, error)
	ListWishesByRoom(ctx context.Context, roomID int64) ([]Wish, error)
	UpsertWish(ctx context.Context, arg UpsertWishParams) (Wish, error)
}

var _ Querier = (*Queries)(nil)
