// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package repository

import (
	"context"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (name, description, created_by)
VALUES ($1, $2, $3)
RETURNING id, created_by, name, description, status, created_at, deleted_at
`

type CreateRoomParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	CreatedBy   int64   `json:"created_by"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom, arg.Name, arg.Description, arg.CreatedBy)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, created_by, name, description, status, created_at, deleted_at
FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id int64) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRoomsByCreator = `-- name: GetRoomsByCreator :many
SELECT id, created_by, name, description, status, created_at, deleted_at
FROM rooms
WHERE created_by = $1
`

func (q *Queries) GetRoomsByCreator(ctx context.Context, createdBy int64) ([]Room, error) {
	rows, err := q.db.Query(ctx, getRoomsByCreator, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT id, created_by, name, description, status, created_at, deleted_at
FROM rooms
ORDER BY created_at DESC
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
