// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (telegram_user_id, username)
VALUES ($1, $2)
ON CONFLICT (telegram_user_id)
DO UPDATE SET username = EXCLUDED.username
RETURNING id, telegram_user_id, username, created_at
`

type CreateUserParams struct {
	TelegramUserID int64   `json:"telegram_user_id"`
	Username       *string `json:"username"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.TelegramUserID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.Username,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT id, telegram_user_id, username, created_at
FROM users
WHERE telegram_user_id = $1
`

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramUserID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramID, telegramUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.Username,
		&i.CreatedAt,
	)
	return i, err
}
