// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wishes.sql

package repository

import (
	"context"
)

const countMissingWishes = `-- name: CountMissingWishes :one
SELECT COUNT(*)
FROM room_members rm
LEFT JOIN wishes w
  ON w.room_id = rm.room_id
 AND w.user_id = rm.user_id
WHERE rm.room_id = $1
  AND w.id IS NULL
`

func (q *Queries) CountMissingWishes(ctx context.Context, roomID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMissingWishes, roomID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWish = `-- name: GetWish :one
SELECT id, room_id, user_id, text, created_at
FROM wishes
WHERE room_id = $1 AND user_id = $2
`

type GetWishParams struct {
	RoomID int64 `json:"room_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetWish(ctx context.Context, arg GetWishParams) (Wish, error) {
	row := q.db.QueryRow(ctx, getWish, arg.RoomID, arg.UserID)
	var i Wish
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const listWishesByRoom = `-- name: ListWishesByRoom :many
SELECT id, room_id, user_id, text, created_at
FROM wishes
WHERE room_id = $1
`

func (q *Queries) ListWishesByRoom(ctx context.Context, roomID int64) ([]Wish, error) {
	rows, err := q.db.Query(ctx, listWishesByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wish
	for rows.Next() {
		var i Wish
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWish = `-- name: UpsertWish :one
INSERT INTO wishes (room_id, user_id, text)
VALUES ($1, $2, $3)
ON CONFLICT (room_id, user_id)
DO UPDATE SET text = EXCLUDED.text
RETURNING id, room_id, user_id, text, created_at
`

type UpsertWishParams struct {
	RoomID int64  `json:"room_id"`
	UserID int64  `json:"user_id"`
	Text   string `json:"text"`
}

func (q *Queries) UpsertWish(ctx context.Context, arg UpsertWishParams) (Wish, error) {
	row := q.db.QueryRow(ctx, upsertWish, arg.RoomID, arg.UserID, arg.Text)
	var i Wish
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}
